debug: False

wandb:
  project: CT_Inpainting
  api_key: c187178e0437c71d461606e312d20dc9f1c6794f
  
training_params:  
  seed: 42
  num_epochs: 100
  learning_rate: 0.0001
  batch_size: 4
  data_dir: 'CT_Inpainting/data'
  train_size: 0.8
  loss_functions: ['l1', 'perceptual'] # you can remove 'perceptual' if you don't want to use it
  perceptual_loss_weight: 0.01
  vgg_layers: [0, 5, 10, 19, 28]

hydra:
  run:
    dir: CT_Inpainting/models/${now:%Y-%m-%d}/${now:%H-%M-%S}




