debug: False

wandb:
  project: CT_Classifier
  api_key: c187178e0437c71d461606e312d20dc9f1c6794f
  
training_params:  
  seed: 42
  num_epochs: 100
  learning_rate: 0.0001
  batch_size: 4
  data_dir: 'CT_Inpainting/data'
  train_size: 0.8
  use_pretrained: True

hydra:
  run:
    dir: CT_Inpainting/classifiers/${now:%Y-%m-%d}/${now:%H-%M-%S}




