method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  base_lr:
    distribution: log_uniform
    min: 1e-6
    max: 1e-4
  max_lr:
    distribution: log_uniform
    min: 1e-3
    max: 1e-1
  adversarial_loss_weight:
    distribution: uniform
    min: 0.01
    max: 0.2
  perceptual_loss_weight:
    distribution: uniform
    min: 0.01
    max: 0.2
